<?php if(empty($this->menu_tree)) { ?>
	<?php $link = __WEB_ROOT_WEB__  .'/'; ?>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="navbar">
		<a class="navbar-brand" href="<?php echo $link ?>"><?php echo tstring('Maternidades robadas'); ?></a>
	</nav>
<?php }else{ ?>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top" id="navbar">
	<?php //  -- navbar navbar-expand-lg navbar-light bg-light -- fixed-top
	$m_main_home = reset($this->menu_tree);
	$link = __WEB_ROOT_WEB__  .'/' ;//. $m_main_home->web_path;
	?>
	<a class="navbar-brand" href="<?php echo $link ?>"><?php echo tstring('Maternidades robadas'); ?></a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" onclick="window.location.href='<?php echo $link ?>';">
		<span class="navbar-toggler-icon"></span>		
	</button>
	<div class="collapse navbar-collapse" id="navbarNavDropdown">
		<ul class="navbar-nav">
		<?php
		function build_li($m_item) {

			$link = __WEB_ROOT_WEB__  .'/'. $m_item->web_path;
			
			$li  = '';
		 	$li .= '<li class="nav-item active">';
			$li .= '<a class="nav-link" href="'.$link.'">'.$m_item->term.' <span class="sr-only">(current)</span></a>';
			$li .= '</li>'.PHP_EOL;
		
			return $li;
		}
		function build_dropdown($m_item, $level=1) {
			$dropdown  = '';
			
			$link = __WEB_ROOT_WEB__  .'/'. $m_item->web_path;

			if ($level===1) {
				$dropdown .= '<li class="nav-item dropdown">';
				$dropdown .= '<a class="nav-link dropdown-toggle" href="'.$link.'" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'.$m_item->term.'</a>';
				$dropdown .= '<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">';
				$dropdown .= '<li><a class="dropdown-item" href="'.$link.'">'.tstring('inicio').'</a></li>';
			}else{
				$dropdown .= '<li class="dropdown-submenu">';
				$dropdown .= '<a class="dropdown-item dropdown-toggle" href="'.$link.'">'.$m_item->term.'</a>';
				$dropdown .= '<ul class="dropdown-menu">';	
			}		   
				foreach ($m_item->childrens_resolved as $ckey => $cm_item) {		    	
					if (empty($cm_item->childrens_resolved)) {
						$link = __WEB_ROOT_WEB__  .'/'. $cm_item->web_path;
						$dropdown .= '<li><a class="dropdown-item" href="'.$link.'">'.$cm_item->term.'</a></li>';		    		
					}else{
						#$dropdown .= '<a class="dropdown-item" href="'.$cm_item->web_path.'">'.$cm_item->term.'</a>';
						$dropdown .= build_dropdown($cm_item, $level+1);
					}
				}		    
				$dropdown .= '</ul>';
				$dropdown .= '</li>';

			return $dropdown;
		}	

		if (isset($m_main_home->childrens_resolved)) {			
			$first_level = $m_main_home->childrens_resolved;
			foreach ((array)$first_level as $key => $m_item) {
				if (empty($m_item->childrens_resolved)) {
					echo build_li($m_item);
				}else{
					echo build_dropdown($m_item);
				}
			}//end foreach ((array)$this->menu_tree as $key => $value)
		}
		?>
		<?php /*
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown link</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">          
					<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Submenu</a>
						<ul class="dropdown-menu">
							<li><a class="dropdown-item" href="#">Submenu action</a></li>
							<li><a class="dropdown-item" href="#">Another submenu action</a></li>
							<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Subsubmenu</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" href="#">Subsubmenu action</a></li>
									<li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
								</ul>
							</li>
							<li class="dropdown-submenu"><a class="dropdown-item dropdown-toggle" href="#">Second subsubmenu</a>
								<ul class="dropdown-menu">
									<li><a class="dropdown-item" href="#">Subsubmenu action</a></li>
									<li><a class="dropdown-item" href="#">Another subsubmenu action</a></li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>
			</li>
			*/ ?>
		</ul>
	</div>
</nav>
<?php /*
<script>
$('.dropdown-menu a.dropdown-toggle').on('click', function(e) {
	if (!$(this).next().hasClass('show')) {
		$(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
	}
	var $subMenu = $(this).next(".dropdown-menu");
	$subMenu.toggleClass('show');


	$(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function(e) {
		$('.dropdown-submenu .show').removeClass("show");
	});


	return false;
});
</script>
*/ ?>
<?php }//if(empty($this->menu_tree)) { ?>