<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Cu rent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- wrapper -->
	<div id="wrapper">

		<!-- Header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<?php /*
		<!-- lang switcher -->
			<ul id="page_lang_selector" class="page_lang_selector">
				<li id="lang_globe"><i class="fa fa-globe"></i></li>
				<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
				<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
				<?php }// end foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) ?>
			</ul>
		*/ ?>

		<!-- Main -->
			<div id="main">
				<h1 class="hide">Numisdata</h1>
				<div class="inner">
					<!-- home image random -->
					<a id="image_wrapper" class="img-wrapper"></a>
					<div class="column_right">
						<!-- form -->
						<div id="form_container"></div>
						<!-- body text -->
						<div class="body_text"><?php echo $body ?></div>
					</div>
					<?php #echo $body ?>
					<?php /*
						<!-- tiles -->
						<header>
							<h1>Áreas</h1>
							<p></p>
						</header>
						<section class="tiles">
							<?php foreach ($menu_items as $key => $item) { ?>
							<article class="style1+">
								<span class="image">
									<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/images/pic01.jpg" alt="" />
								</span>
								<a href="<?php echo __WEB_ROOT_WEB__ . '/' . $item->web_path ?>" rel="noreferrer">
									<h2><?php echo $item->term ?></h2>
									<div class="content">
										<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
									</div>
								</a>
							</article>
							<?php }//end foreach ($menu_items as $key => $item) ?>
						</section>
						*/ ?>
				</div>
			</div>

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	main_home.set_up({
		form_container	: document.getElementById('form_container'),
		image_wrapper	: document.getElementById('image_wrapper'),
		ar_images		: <?php echo json_encode($ar_images) ?>
	})
})
</script>