<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- wrapper -->
	<div id="wrapper">

		<!-- Header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			<div id="main">
				<div class="inner">
					<h1><?php echo $title ?></h1>
					
					<?php /*<span class="image main"><img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/home2.jpg" alt="" /></span>*/ ?>

					<!-- tiles -->
				

					<!-- body text -->
					<p><?php echo $body ?></p>


					<!-- tiles -->
						<?php /*
						<header>
							<h1>Áreas</h1>
							<p></p>
						</header>
						<section class="tiles">							
							<?php foreach ($menu_items as $key => $item) { ?>						
							<article class="style1+">
								<span class="image">
									<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/images/pic01.jpg" alt="" />
								</span>
								<a href="<?php echo __WEB_ROOT_WEB__ . '/' . $item->web_path ?>">
									<h2><?php echo $item->term ?></h2>
									<div class="content">
										<p>Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat.</p>
									</div>
								</a>
							</article>
							<?php } ?>							
						</section>
						*/ ?>
				</div>


			</div>

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>
	</div>

<?php echo $this->get_header_links('js') ?>
<script>
document.addEventListener('DOMContentLoaded', function(event) {
	console.log("main_home loaded!");
})
</script>