<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- Form -->
					<section class="form">
						<?php #include($cwd.'_search.phtml') ?>
						<div id="items_container"></div>
					</section>



					<!-- Result -->
						<section class="result">
							<div id="rows_list" class="rows_list"></div>
							<div id="export_data" class="export_data_container"></div>
						</section>

				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	catalog.set_up({
		psqo					: <?php echo json_encode($psqo) ?>,
		rows_list_container		: document.getElementById('rows_list'),
		export_data_container	: document.getElementById('export_data'),
		form_items_container	: document.getElementById('items_container')
	})
})
</script>
