<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>

					<!-- Form -->
					<section class="form">
						<?php #include($cwd.'_search.phtml') ?>
						<div id="items_container"></div>
					</section>

					

					<!-- Result -->
						<section class="result">
							<div id="rows_list"></div>
						</section>

				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js') ?>
<script>
document.addEventListener('DOMContentLoaded', function(event) {
	catalog.set_up({
		global_search : <?php echo json_encode($global_search) ?>
	})
})
</script>