<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="page-wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main wrapper -->
			<div class="wrapper">
				<div class="container">
					<article id="main">

					<!-- title -->
						<h2><?php echo $title ?></h2>

					<!-- Form -->
						<section class="form">
							<div id="items_container"></div>
							<div id="view_options"></div>
						</section>

					<!-- Result -->
						<section class="result">
							<div id="rows_list"></div>
						</section>

				</article>
				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	thesaurus.set_up({
		table		: <?php echo json_encode($thesaurus_options->table) ?>,
		root_term	: <?php echo json_encode($thesaurus_options->root_term) ?>,
		term_id		: <?php echo json_encode($thesaurus_options->term_id) ?>,
		rows_list	: document.getElementById('rows_list') 
	})	
})
</script>
