<?php
# REQUIRED FILES
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- Form -->
						<section class="form">
							<div id="items_container"></div>
							<div id="view_options"></div>
						</section>

					<!-- Result -->
						<section class="result">
							<div id="rows_list"></div>
						</section>

				</article>
				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	thesaurus.set_up({
		table		: <?php echo json_encode($thesaurus_options->table) ?>,
		root_term	: <?php echo json_encode($thesaurus_options->root_term) ?>,
		term_id		: <?php echo json_encode($thesaurus_options->term_id) ?>,
		ar_fields	: <?php echo json_encode($thesaurus_options->ar_fields) ?>,
		rows_list	: document.getElementById('rows_list')
	})
})
</script>