<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?><img id="search_icon" class="search_icon" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/icon_search.svg"></h1>

					<!-- form -->
						<div id="form_container" class=""></div>

					<!-- map -->
						<div id="map_container" class="map_container hide_opacity map full_width"></div>

					<!-- result -->
						<section id="rows_container" class="result rows_list"></section>

					<!-- export_data -->
						<div id="export_data" class="export_data_container"></div>

				</div>
			</div>


		<!-- footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	map.set_up({
		form_container			: document.getElementById('form_container'),
		rows_container			: document.getElementById('rows_container'),
		map_container			: document.getElementById('map_container'),
		export_data_container	: document.getElementById('export_data'),
	})
})
</script>