<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- content -->
						<div id="content">
							<section class="content_body">

								<!-- search form container -->
									<div class="thematic_search_form">
										<form id="form_thematic">
											<!-- <label><?php echo tstring('filter') ?></label>-->
											<input type="text" name="q" class="q" value="<?php echo htmlspecialchars($q_raw) ?>" id="input_search" placeholder="<?php echo $placeholder ?? '' ?>">
											<input type="submit" class="gen_button submit" value="<?php echo tstring('search') ?>">
											<input type="button" class="gen_button reset" value="<?php echo tstring('reset') ?>" onclick="search_thematic.reset_tree(this)">
										</form>
									</div>



								<!-- tree -->
									<div id="wrapper_tree">

										<?php
										#
										# ROOT TESAURUS
										$html = '';
										#$html .= "<div id=\"jer_title\">".tstring('Descriptores temáticos')." </div>";
										#dump($ar_ts_terms, ' ar_ts_terms ++ '.to_string());
										$parent_name=array();
										foreach ($ar_ts_terms as $tld => $ar_value) {
											#dump($ar_value, ' ar_value ++ '.to_string($tld));
											$html .= "<ul id=\"ul_{$tld}\" class=\"ts_term_ul\">";
											foreach ($ar_value as $key => $data_object) {
												// dump($data_object, '$data_object ++ '.to_string());

												# web_ts_term . Build ts_term html object
												$web_ts_term = new web_ts_term($data_object);
												if ($q) {
													$options_web_ts_term = new stdClass();
														$options_web_ts_term->open_childrens = true;
													$web_ts_term->options = $options_web_ts_term;
														#dump($web_ts_term, ' web_ts_term ++ '.to_string($data_object));
												}
												$html .= $web_ts_term->get_html();
											}
											$html .= "</ul>";
										}
										echo $html;
										?>
									</div><!-- /wrapper_tree -->


								<div class="clearfix"></div>


								<!-- pagination -->
									<?php
									#
									# Pagination
									# dump($response, ' response ++ '.to_string());
									$data = isset($response->search_data) ? $response->search_data : false;
									if (!empty($data)) {
										echo page::get_pagination($data, 10); // $search_data, $max_pages=null, $crumbs=null
									}
									?>

							</section>
						</div>

				</div>
			</div>

		<!-- footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script type="text/javascript">
<?php
#
# JAVASCRIPT CODE

	#
	# AR_HIGHLIGHT
	# Set web_indexation_node elements to open by javascript when init web_ts_term.js
	# See web_ts_term : document.ready functions
	if (isset($response->ar_highlight)) {

		$ar_highlight_json = json_encode($response->ar_highlight);
		echo " var ar_highlight='{$ar_highlight_json}';";
		#echo "	console.log(ar_highlight);";
	}
	#
	# AR_PARENT
	# Set web_ts_term elements to open by javascript when init web_ts_term.js
	# See web_ts_term : document.ready functions (web_ts_term_to_open test)
	if (isset($response->ar_parent)) {

		echo " ar_childrens_loaded={};";
		echo " web_ts_term_to_open={";
		foreach ((array)$response->ar_parent as $current_parent) {
			echo "'".$current_parent."':'loaded',";
		}
		echo "};";
		//echo " console.log(web_ts_term_to_open) ";
	}
	#echo "; console.log(".json_encode($response).")";
?>
</script>