<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>

					<!-- Form -->
					<section class="form">
						<?php # include($cwd.'_search.phtml') ?>
					</section>

					<!-- Result -->
						<section class="result">
							<div id="mints_rows_list"> <span>Loading rows..</span> </div>
						</section>

				</div>
			</div>


		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js') ?>
<script type="text/javascript" src="<?php echo __WEB_TEMPLATE_WEB__ . '/' . $cwd ?>/js/row_fields.js"></script>
<script>
	mints.set_up({})
</script>
