<?php
$html = '';


if (!empty($this->illustration)) {

		$dd_relations = json_decode($this->dd_relations);
		//get legends id
		$ar_legends_locators = array_filter($dd_relations, function($locator){
			return ($locator->from_section_tipo === 'numisdata41' ) ? $locator : false ;
		});

		$legends = array_map(function($locator){
			return (int)$locator->from_section_id;
		}, $ar_legends_locators);

		$legends = array_values($legends);

		//get countermark id
		$ar_cmk_locators = array_filter($dd_relations, function($locator){
			return ($locator->from_section_tipo === 'numisdata4' ) ? $locator : false ;
		});

		$countermarck = array_map(function($locator){
			return (int)$locator->from_section_id;
		}, $ar_cmk_locators);

		$countermarck = array_values($countermarck);

		$image_url = __WEB_BASE_URL__ . '/' . $this->illustration;


		$html .= "<li class=\"web_ts_illustation_li clearfix\">";
			$html .= "<img id=\"button_toggle_indexation_{$this->term_id}\" ";
			$html .= "class=\"icon_show_illustration unselectable tooltip\" ";
			// $html .= "rel=\"tooltip\" ";
			// $html .= "title=\"" . tstring('mostrar_ilustacion') . "\" ";
			$html .= "onclick=\"web_ts_term.toggle_indexation(this)\" ";
			$html .= "data-term_id=\"" . $this->term_id  . "\" ";
			$html .= "data-ar_legends=\"" . json_encode($legends) . "\" ";
			$html .= "data-ar_cmk=\"" . json_encode($countermarck) . "\" ";
			$html .= "src=\"".$image_url. "\" ";
			$html .= "></img>";

			#
			# INDEX_WRAPPER
			$html .= "<div id=\"index_wrapper_{$this->term_id}\" class=\"index_wrapper hidden\"></div>";
		$html .= "</li>";
	
}else{
	$html .= "<li class=\"web_ts_term_li clearfix\">";

	#
	# TERM Name
	#dump($this->options, ' this->options ++ '.to_string());
	$add_class = '';
	if (isset($this->highlight)) {
		$add_class = 'highlight_term';
	}
	$html .= "<div id=\"web_ts_term_".$this->term_id."\" class=\"web_ts_term_name $add_class\">";
	$html .= $this->term;
	if(SHOW_DEBUG===true) {
		$html .= " <small>[".$this->term_id."]</small>";
	}
	$html .= "</div>";


	#
	# CHILDRENS TOGGLE BUTTON
	# note that $this->ar_childrens is a php array
	if (!empty($this->ar_childrens)) {
		$ar_childrens_json = json_encode($this->ar_childrens);
		$title = tstring('mostrar_ocultar_temas');
		$html .= "<div class=\"web_ts_term_icon icon_show_childrens arrow_right unselectable tooltip\" ";
		$html .= "rel=\"tooltip\" ";
		$html .= "title=\"$title\" ";
		$html .= "data-term_id=\"$this->term_id\" ";
		$html .= 'data-ar_childrens=\''.$ar_childrens_json.'\' ';
		$html .= "onclick=\"web_ts_term.toggle_childrens(this)\" ";
		$html .= "></div>";
	}


	$html .= "</li>";


	#
	# CHILDRENS_WRAPPER . Ajax target to load childrens
	$html .= "<ul id=\"childrens_wrapper_{$this->term_id}\" class=\"childrens_wrapper\"></ul>";
}





#
# OPEN CHILDRENS FORCE
/*
if (isset($this->options->open_childrens)) {
	$html .= "<script>if(!web_ts_term_to_open) var web_ts_term_to_open={}; web_ts_term_to_open['$this->term_id'] = '{$this->term_id}';</script>";
}
*/

echo $html;
?>