<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Curent controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- main -->
			<div id="main">
				<div class="inner">

					<!-- Result -->
						<section class="result">
							<div id="row_detail"> <span>Loading row..</span> </div>
						</section>

				</div>
			</div>


		<!-- footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js') ?>
<script>
document.addEventListener('DOMContentLoaded', function(event) {
	type.set_up({
		section_id : '<?php echo $section_id ?>'
	})
})
</script>