<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
<?php 
	$m_main_home = reset($this->menu_tree);
?>
<a class="navbar-brand" href="<?php echo $m_main_home->web_path ?>"><?php echo $m_main_home->term ?></a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_default" aria-controls="navbar_default" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbar_default">
<ul class="navbar-nav mr-auto">
	<?php
	function build_dropdown($m_item, $level=1) {
		$dropdown  = '';
		$dropdown .= '<li class="nav-item dropdown">';
	    $dropdown .= '<a class="nav-link dropdown-toggle" href="'.$m_item->web_path.'" id="dropdown_{$key}_{$$level}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'.$m_item->term.'</a>';
	    $dropdown .= '<div class="dropdown-menu" aria-labelledby="dropdown_{$key}_{$$level}">';
	    foreach ($m_item->childrens_resolved as $ckey => $cm_item) {
	    	
	    	if (!empty($cm_item->childrens_resolved)) {
	    		#$dropdown .= '<a class="dropdown-item" href="'.$cm_item->web_path.'">'.$cm_item->term.'</a>';
	    		$dropdown .= build_dropdown($cm_item, $level+1);
	    	}else{
	    		$dropdown .= '<a class="dropdown-item" href="'.$cm_item->web_path.'">'.$cm_item->term.'</a>';
	    	}
	    }		    
	    $dropdown .= '</div>';
	  	$dropdown .= '</li>';

	  	return $dropdown;
	}
	function build_li($m_item) {
		$li  = '';
		$li .= '<li class="nav-item active">';
    	$li .= '<a class="nav-link" href="'.$m_item->web_path.'">'.$m_item->term.' <span class="sr-only">(current)</span></a>';
  		$li .= '</li>';
		
		return $li;
	}


	$first_level = $m_main_home->childrens_resolved;
	foreach ((array)$first_level as $key => $m_item) {

		if (!empty($m_item->childrens_resolved)) {
			echo build_dropdown($m_item);
		}else{
			echo build_li($m_item);			
		}
		
	}//end foreach ((array)$this->menu_tree as $key => $value)

	/*
	?>
  <li class="nav-item active">
    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
  */ ?>
  <?php /*
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
    <div class="dropdown-menu" aria-labelledby="dropdown01">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li>*/ ?>

</ul>
<?php /*
<form class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
*/ ?>
</div>
</nav>