<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	// Current controller add
	require($base_path .'/'. $cwd .'.php');
?>

<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>


		<!-- main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- abstract -->
						<?php if(!empty($abstract)) { ?>
						<p><?php echo $abstract ?></p>
						<?php } ?>

					<!-- Form -->
						<div id="form_container"></div>

					<!-- Result -->
						<section id="rows_container" class="result"></section>

				</div>
			</div>


		<!-- footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	coins.set_up({
		psqo			: <?php echo json_encode($psqo) ?>,
		form_container	: document.getElementById('form_container'),
		rows_container	: document.getElementById('rows_container')
	})
})
</script>