<?php
# REQUIRED FILES
	$base_path = dirname(dirname(__FILE__));
	$cwd 	   = basename($base_path); # Current dir name

	# Current controller add
	require($base_path .'/'. $cwd .'.php');
?>
<!-- Wrapper -->
	<div id="wrapper">

		<!-- header -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/header.phtml'; ?>

		<!-- Main -->
			<div id="main">
				<div class="inner">

					<!-- title -->
						<h1><?php echo $title ?></h1>
						<div class="golden-separator"></div>

					<!-- Form -->
						<section class="form">
							<?php #include($cwd.'_search.phtml') ?>
							<div id="items_container"></div>
						</section>

					<!-- Result -->
						<section id="result" class="result">
							<div id='weight_section' class='hide'>
								<div class="info_line separator"><div class="big_label"><?php echo tstring('weight')?></div></div>
								<div id="weight_chart_container" class="chart_wrapper"></div>
							</div>
							<div id="diameter_section" class="hide">
								<div class="info_line separator"><div class="big_label"><?php echo tstring('diameter')?></div></div>
								<div id="diameter_chart_container" class="chart_wrapper"></div>
							</div>
							<div id="clock_section" class="hide">
								<div class="info_line separator"><div class="big_label"><?php echo tstring('die_position')?></div></div>
								<div id="clock_chart_container" class="chart_wrapper"></div>
							</div>
							<!-- <div id="export_data" class="export_data_container"></div> -->
						</section>

				</div>
			</div>

		<!-- Footer -->
			<?php include dirname(dirname(dirname(__FILE__))) . '/page/html/footer.phtml'; ?>

	</div>

<?php echo $this->get_header_links('js', ['js_async' => 'defer']) ?>
<script>
dom_ready(function(){
	var analysis = analysis_min.analysis
	analysis.set_up({
		row							: <?php echo json_encode($this->row) ?>,
		area_name					: <?php echo json_encode($area_name) ?>,
		export_data_container		: document.getElementById('export_data'),
		form_items_container		: document.getElementById('items_container'),
		weight_chart_container		: document.getElementById('weight_chart_container'),
		diameter_chart_container	: document.getElementById('diameter_chart_container'),
		clock_chart_container		: document.getElementById('clock_chart_container')
	})
})
</script>