<?php


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?php echo $lang_iso_2 ?>" xml:lang="<?php echo $lang_iso_2 ?>">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><?php echo $page_title ?></title>
<style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Open+Sans);
html {
	font-family: 'Open Sans',verdana,sans-serif;font-style:normal;font-weight:400;font-size:13px;color:#666;
}
body { 
	margin:0; padding:0; line-height:1.2em; width:100%; /*min-width:1120px;*/ 
	background-color:rgb(255,255,255);
}
.footer { font-size:12px;}
p.msg { color:#333333; margin-top:20px; margin-bottom:20px;}
p.link { margin-right:5px; margin-top:30px; margin-bottom:35px; word-break: normal  }
img { margin: 0; padding: 0; width: 820px; height: 95px}
.content { padding-left: 15px}
</style>

</head>
<body>
<div class="wrap bg_ramp">
	
	<img src="http://www.mujerymemoria.org/web/images/logo_mail.jpg" />
    
<!-- content -->
	<div class="content">

			<!-- title -->
	    		<p><strong><?php echo $page_title ?></strong></p>

			<!-- msg label -->
				<p>			
				<?php
					switch ($lang) {
						case 'lg-eng':
							?>
							A friend recommends this video from the web MujeryMemoria.org. Click the link to view it.<br />
							(If it does not work, copy the address and paste it into the address bar of your browser).
							<?php
							break;
						
						case 'lg-spa':
						default:
							?>
							Un amigo le ha recomendado este vídeo desde la web MujeryMemoria.org. Pulse en el enlace para visualizarlo.<br />
							(Si no le funciona, copie la dirección y péguela en la barra de direcciones de su navegador).
							<?php
							break;
					}
				?>
				</p>

			<!-- msg body -->
				<p class="msg"><?php echo $msg ?></p>

			<!-- video link -->
				<p class="link"><a href="<?php echo $video_url ?>" target="_blank" title="Open url"><?php echo $video_url ?></a></p>

			<!-- footer -->
				<div class="footer">
					<p><a href="http://www.mujerymemoria.org" title="www.mujerymemoria.org" target="_blank">www.mujery memoria.org</a><br />
					<a href="mailto:webmaster@mujerymemoria.org" title="webmaster@mujerymemoria.org">webmaster@mujerymemoria.org</a></p>
				</div>
      
            
    </div><!-- /content -->

</div><!-- /wrap -->
</body>
</html>