<footer id="footer">
	
	<!-- Moneda Ibérica -->
		<section>
			<h2>Moneda Ibérica</h2>
		</section>
		
	<!-- inner -->
		<div class="inner">
			
			<?php /*
			<section>
				<h2>Get in touch</h2>
				<form method="post" action="#">
					<div class="fields">
						<div class="field half">
							<input type="text" name="name" id="name" placeholder="Name" />
						</div>
						<div class="field half">
							<input type="email" name="email" id="email" placeholder="Email" />
						</div>
						<div class="field">
							<textarea name="message" id="message" placeholder="Message"></textarea>
						</div>
					</div>
					<ul class="actions">
						<li><input type="submit" value="Send" class="primary" /></li>
					</ul>
				</form>
			</section>
			
			<section>
				<h2><?php #echo tstring('siguenos') ?></h2>
				<ul class="icons">
					<li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon style2 fa-github"><span class="label">GitHub</span></a></li>
					<?php //<li><a href="#" class="icon style2 fa-500px"><span class="label">500px</span></a></li> ?>
					<li><a href="#" class="icon style2 fa-phone"><span class="label">Phone</span></a></li>
					<li><a href="#" class="icon style2 fa-envelope-o"><span class="label">Email</span></a></li>
				</ul>
			</section>
			*/ ?>

			<!-- logos -->
				<ul class="logos">
					<li class="ministerio">
						<a href="http://www.ciencia.gob.es/portal/site/MICINN/" rel="noreferrer" target="_blank"></a>			
					</li>
					<li class="uni_val_hist">
						<a href="https://www.uv.es/uvweb/geografia-historia/ca/departaments/llista-departaments/prehistoria-arqueologia-historia-antiga-1285849132686.html" rel="noreferrer" target="_blank"></a>			
					</li>				
					<li class="mupreva">
						<a href="http://www.mupreva.org/" rel="noreferrer" target="_blank"></a>			
					</li>
					<li class="render">
						<a href="http://www.render.es/" rel="noreferrer" target="_blank"></a>			
					</li>
				</ul>

			<ul class="copyright">
				<li>&copy; Numisdata.org</li>
				<li>Powered by: <a href="http://fmomo.org" rel="noreferrer" target="_blank">Dédalo Cultural Heritage Management Platform</a></li>
			</ul>
		</div>
</footer>