<footer id="footer" class="hidded">
	<!-- inner -->
	<div class="inner">
		<div class="footer-section-wrapper" id="footer_dynamic_wraper"></div>
		<div class="footer-copyright-wrapper">
			<ul class="copyright version">
				<li>Numisdata web v <?php
					echo WEB_VERSION;
					echo IS_PRODUCTION ? ' pro' : ' dev';
					if (IS_PRODUCTION===false) {
						echo ' DB: '.WEB_DB;
					}
				?></li><?php
					if (defined('ISSB_ISSN') && !empty(ISSB_ISSN)) {
						$html	= '<li>';
							$html	.= '<a href="'.ISSB_ISSN_URI.'" class="issb_issn" rel="noreferrer" target="_blank">';
								$html	.= 'ISSB_ISSN ';
							$html	.=  '</a>';
						$html	.= '</li>';

						echo $html;
					}
				?>
				<li><a href="mailto:<?php echo EMAIL ?>"><?php echo EMAIL ?></a></li>
				<li class="print_hide99">
					Powered by
					<a href="https://dedalo.dev" rel="noreferrer" target="_blank">
						<img class="logo_dedalo" src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_dedalo_white.svg" loading="lazy">
						Dédalo Cultural Heritage Management Platform
					</a>
				</li>
			</ul>
		</div>
	</div>
</footer>
<?php page::$js_ar_url[] = __WEB_TEMPLATE_WEB__ . '/page/js/footer'.JS_SUFFIX.'.js'; ?>
<script>
dom_ready(function(){
	footer.set_up({
		footer_root				: <?php echo json_encode($this->footer_root) ?>,
		footer_data				: <?php echo json_encode($this->footer_data) ?>,
		footer_dynamic_wraper	: document.getElementById('footer_dynamic_wraper')
	})
})
</script>
