<!-- Header -->
	<header id="header">
		<div class="head_inner">

			<?php if (strpos(__WEB_ROOT_WEB__, '/pre/')!==false) { ?>
				<div class="pre_alert"></div>
			<?php } ?>

			<!-- FOR RETURN TO ANTERIOR MAIN HOME LOGO CHANGE area_name=== to "main_home" -->
			<?php /*if ($this->area_name==='main_home') { ?>

				<!-- Logo -->
					<div class="logo_big">
						<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_mib_marron.svg" alt="" />
					</div>

				<!-- Nav -->
					<nav>
						<ul>
							<li><a href="#menu"><?php echo tstring('menu') ?></a></li>
						</ul>
					</nav>

			<?php }else{ */?>

				<!-- Logo -->
					<a href="<?php echo __WEB_ROOT_WEB__ ?>" class="logo">
						<?php /*
						<!-- <span class="symbol"> -->
						<!-- <img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/logo_mib_marron.svg" alt="" /> -->
						<!-- <img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/mib_header.svg" alt="" /> -->
						*/ ?>
						<span class="title"></span>
					</a>

				<!-- Nav -->
					<nav>
						<ul>
							<li><a href="#menu"><?php echo tstring('menu') ?></a></li>
						</ul>
					</nav>

				<!-- Warning work in progress -->
					<!-- <div class="header_warning">

						<img src="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/images/Work_In_Progress.png">
						<span><?php echo tstring('work_in_progress'); // 'Work in progress. Provisional numbering. Not for citation' ?></span>

					</div>
					-->

			<?php /* } //if ($this->area_name==='main_home') { */?>
		</div>
	</header>

<!-- Menu -->
	<nav id="menu">
		<!-- lang switcher -->
			<div id="lang_globe" class="lang_globe" title="Switch lang">
				<span><?php echo tstring('lang');?></span>
				<i class="fa fa-globe"></i>
			</div>
			<ul id="page_lang_selector" class="page_lang_selector hide">
				<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
					<li class="lang_item"><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
				<?php } ?>
			</ul>
		<h2><?php echo tstring('menu') ?></h2>
		<?php echo $this->menu_tree_html ?>
	</nav>

	<?php /*
	<!-- lang switcher -->
	<ul id="page_lang_selector">
		<li id="lang_globe"><i class="fa fa-globe"></i></li>
		<?php foreach (json_decode(WEB_AR_LANGS) as $lang => $lang_name) { ?>
		<li><a href="?lang=<?php echo $lang ?>"><?php echo $lang_name ?></a></li>
		<?php } ?>
	</ul>
	*/ ?>