<?php
# included files
	$base_path	= dirname(dirname(__FILE__));
	$cwd		= basename($base_path); # Current dir name

	# Current controller add
	include($base_path .'/'. $cwd .'.php');
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $page_title ?></title>
	<link rel="preconnect" href="<?php echo __WEB_MEDIA_BASE_URL__ ?>">
	<link rel="dns-prefetch" href="<?php echo __WEB_MEDIA_BASE_URL__ ?>">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="dns-prefetch" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="dns-prefetch" href="https://fonts.gstatic.com">
	<link rel="preconnect" href="https://api.maptiler.com">
	<link rel="dns-prefetch" href="https://api.maptiler.com">
	<link rel='shortcut icon' type='image/x-icon' href='<?php echo __WEB_TEMPLATE_WEB__ ?>/favicon.ico' />
	<!-- Include StyleSheets -->
	<?php echo $css_links ?>
	<link rel="preload" href="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/lib/jquery-ui/jquery-ui.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
	<noscript><link rel="stylesheet" href="<?php echo __WEB_TEMPLATE_WEB__ ?>/assets/lib/jquery-ui/jquery-ui.min.css"></noscript>
	<?php #include $base_path . '/html/favicons.phtml'; ?>
	<!-- JS environmental vars -->
	<script rel="preload" src="<?php echo __WEB_TEMPLATE_WEB__ . '/page/js/enviroment.js.php' ?>"></script>
	<script>
		var WEB_AREA='<?php echo $this->area_name ?>'
	</script>
</head>
<body class="is-preload">
<!--[if lt IE 8]>
	<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->
<?php echo $content_html ?>
<script>
dom_ready(function(){
	page.setup()
})
</script>
<?php // analytics
if(IS_PRODUCTION===true) {
	// include $base_path . '/html/matomo_analytics.inc';
}
?>
</body>
</html>